name: ux5x5
favicon: null
layout_spectrum: 0.50191
typography_spectrum: 0.61758
title: UX5x5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d5145'
    - '#1f1b1c'
    - '#fffef3'
    - '#a48570'
    - '#d0b29a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
