name: ux5x5
favicon: null
layout_spectrum: 0.76004
typography_spectrum: 0.61758
title: UX5x5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfc3ac'
    - '#808c82'
    - '#d0846c'
    - '#605f65'
    - '#3b7adb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
