name: ux5x5
favicon: null
layout_spectrum: 0.50191
typography_spectrum: 0.26768
title: UX5x5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#dacbac'
    - '#92928a'
    - '#f3691e'
    - '#3c68b3'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
